services:
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/test
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      OSRM_URL: http://osrm:5000
    volumes:
      - ./host_downloads:/root/RawImages
    depends_on:
      - mongo
      - osrm
    networks:
      - app-network

  osrm:
    restart: always
    image: osrm/osrm-backend
    container_name: osrm
    volumes:
      - ./osrm-data:/data
    ports:
      - "5000:5000"
    command: osrm-routed --algorithm mld /data/tennessee-latest.osrm
    networks:
      - app-network

  mongo:
    restart: always
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge